### ISSUE TITLE
Some feature not working

### ISSUE THREAD

**Issue by thanhlouis** [JoakimCarlsson/ShopTitansTrainer#2]
Not work:
- Search item in craft box not work correctly
- Quest component
- Surcharge or discount (some time discount but never surcharge)
- Can't open options
- On;y craft common item, can't see the glitch
Work:
- Auto sell item
- Craft
Thanks your mod !

**Comment by thanhlouis** [comment]
On;y craft common item, can't see the glitch
Sorry my resolution not show the quality box haha

**Comment by JoakimCarlsson** [comment]
- Search item in craft box
It does work, but in a weird way. I'll have too fix that. But, Herb != herb. 
So, if you were looking for something with 'Herb' you would have too type 'Herb' and not herb.

- Quest component
The code for quest is not there, after the last update I had some weird glitches. But i'll implement it back.

- Can't open options
Options should work, it works perfectly for me. I'll have too check that one out.

- Only craft common item
The way glitch craft work is like this.
1. Open Craft Component.
2. Select an item from the Crafting Window. 
3. Select the quality from Quality Window. 
4. Once you select you should see your item in the windows such as **Nightmare Element, Flawless** (or what ever you choose)
5. Repeat from step 2.
