### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by thanhlouis** [JoakimCarlsson/ShopTitansTrainer#3]
Can you make a guide to compile your project. I'm newbie, installed unity and visual studio but I can't build this project. I want to edit the unity menu because my monitor too small so I can't see the quality box :(

**Comment by JoakimCarlsson** [comment]
1. Open the project in visual studio.
2. Add the missing references from the Managed folder where your game is installed.

**Comment by thanhlouis** [comment]
Thank you very much. Done

**Comment by Oratorian** [comment]
Sry to reply here, but i dont have the managed folder in my ShopTitans install location
