### ISSUE TITLE
Glitch Crafting

### ISSUE THREAD

**Issue by itzKyler** [JoakimCarlsson/ShopTitansTrainer#4]
Glitch Crafting doesn't work, I feel like servers have been patched, I tried modifying code, but no success.
I saw someone had the same issue earlier, used the guide you told him to follow but still, had no success.
Game has to reconnect as soon as craft is toggled.

Still excellent release ! thanks for your work !

**Comment by JoakimCarlsson** [comment]
That's odd. I'm using it right  now without any  issues.  Do you have
Discord so I can contact you?

**Comment by itzKyler** [comment]
Weird.. of course here : Ky#6100
