### ISSUE TITLE
Not sure how to run this

### ISSUE THREAD

**Issue by NiceKallex** [JoakimCarlsson/ShopTitansTrainer#9]
Hi

I have been trying to compile your source code in my VS, but without any luck. I've downloaded some packages, but it still doesn't seem to be enough. I still have a lot of red lines in both the code itself and some usings. 
I see that I am not the only one having this issue.

What do we need to make this run properly?

**Comment by JoakimCarlsson** [comment]
Sadly the game have moved onto il2cpp, and this trainer is as of right now outdated.
